spring:
  application:
    name: community-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME:local}
    password: ${RDS_PASSWORD:local}
    url: jdbc:mysql://${RDS_ENDPOINT:localhost}:3307/community?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

  jwt:
    secret-access: ${ACCESS_SECRET}
    secret-refresh: ${REFRESH_SECRET}
    access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

  mail:
    host: smtp.naver.com
    port: ${NAVER_MAIL_PORT}
    username: ${NAVER_ID}
    password: ${NAVER_PW}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          connectionTimeout: ${TIMEOUT}
          timeout: ${TIMEOUT}
          writeTimeout: ${TIMEOUT}
        debug: true

security:
  jwt-filter:
    exclude-paths:
      - /actuator/**
      - /docs/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /error

      # 공개 API
      - /api/v1/auth/**
      - /api/v1/categories/**
      - /api/v1/products/**
      - /api/v1/orders/**
      - /api/v1/payments/**
      - /_fake_toss/**

      # 정적 리소스
      - /checkout.html
      - /favicon.ico
      - /v1
      - /v1/**
      - /log
      - /logs
      - /logs/**
    exclude-methods:
      - OPTIONS
    access-token-cookie: null

auth:
  email: # ← EmailVerificationProperties(@ConfigurationProperties) 바인딩
    code-ttl: 5m                        # Duration 타입: 5분
    cooltime: 60s                       # 재요청 쿨타임
    max-attempts: 5                     # 최대 인증 시도
    block-ttl: 10m                      # 시도 초과 차단 시간
    verified-ttl: 10m                   # 검증 성공 플래그 TTL

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE

#toss:
#  base-url: http://localhost:8080/_fake_toss
#  secret-key: test_sk_dummy
toss:
  base-url: https://api.tosspayments.com
  clientKey: test_gck_docs_Ovk5rK1EwkEbP0W43n07Xlzm
  secretKey: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: "%t %m %U %s"