spring:
  application:
    name: community-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME:local}
    password: ${RDS_PASSWORD:local}
    url: jdbc:mysql://${RDS_ENDPOINT:localhost}:3307/community?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        open-in-view: false

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

  jwt:
    secret-access: ${ACCESS_SECRET}
    secret-refresh: ${REFRESH_SECRET}
    access-token-expiration: ${ACCESS-TOKEN-EXPIRATION}
    refresh-token-expiration: ${REFRESH-TOKEN-EXPIRATION}

security:
  jwt-filter:
    exclude-paths:
      - /actuator/**
      - /docs/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /error
      - /api/v1/auth/signup
      - /api/v1/auth/sign-in
      - /api/v1/auth/token/refresh
    exclude-methods:
      - OPTIONS
    access-token-cookie: null